#!/bin/bash

mc_template="config/redhat-wifi.mobileconfig.template"
mc_target="config/generated/redhat-wifi.mobileconfig"

explain_prompt() {
  prompt="Please enter $1 ($2): "
  # $1 <- "your X", "the Y"
  # $2 <- "x", "y"
  read -p "$prompt" val
  echo -n $val
  >&2 printf "\n"
}

generate_mobileconfig() {
  sed "s/__USERNAME__/$1/" $mc_template > $mc_target
}

import_mobileconfig() {
  /usr/bin/profiles -I -F $mc_target
}

remove_mobileconfig() {
  /usr/bin/profiles remove -identifier redhat-mac-wifi-profile
}

wifi_off() {
  printf "[sudo] Turning off your Wi-Fi... "
  sudo networksetup -setairportpower en0 off
}

wifi_on() {
  printf "[sudo] Turning on your Wi-Fi... "
  sudo networksetup -setairportpower en0 on
}