#!/bin/bash

WD=`pwd`; SCRIPT=`realpath $0`; cd `dirname $SCRIPT`
source ./config/helpers

wifi_off

printf "\nRemoving the \"Red Hat\" Wi-Fi Profile... "
remove_mobileconfig && printf "All gone.\n"

wifi_on

printf "Done!\n"

cd $WD
