#!/bin/bash

source ./config/helpers

username=$(explain_prompt "your Red Hat SSO / Kerberos ID" "username")

wifi_off

printf "\nRemoving Red Hat from your preferred networks, just in case...\n"
networksetup -removepreferredwirelessnetwork en0 "Red Hat"

printf "\nInstalling a new \"Red Hat\" Wi-Fi profile... "
generate_mobileconfig $username
import_mobileconfig

printf "\n"
wifi_on
printf "Done!\n"

printf "\nYour Mac will now remember your username without remembering your OTP token! 🎉\n"
printf "\nAuto-join is enabled."
printf "\nIf you are at the office, your system should now try to connect to wi-fi.\n"
